#!/bin/bash
GREEN="\033[1;32m"
NORMAL="\033[0m"

compiler=cc
files=()

usage() {
	cat << _EOF_
Usage: autocompile [OPTION].. [FILE]... -- [COMPILE OPTIONS]...
Watch files and compile them if there's a change.
Front end to inotifywait

View man page for details and examples.
  -h, --help	display this help message and exit
  -c	set a custom compiler
  --	interpret everything following as arguments to the compiler
_EOF_
}

# handle args
while [ -n "$1" ]; do
	case "$1" in
		-h|--help) # print usage info and exit
			usage
			exit
			;;
		-c) # set the compiler to something other than cc
			shift
			compiler="$1"
			;;
		--)
			shift
			break
			;;
		-*)
			echo argument "$1" is not a valid argument
			;;
		*) # Assume arg is file. Pass to compiler
			files+=("$1")
			;;
	esac
	shift
done

# compile once before waiting starts
$compiler "$@" "${files[@]}"

# watch files
while inotifywait -e modify,move_self "${files[@]}"; do
	# print divider
	printf "$GREEN"
	printf "=%.0s" `seq $COLUMNS`
	printf "$NORMAL\n"

	for i in "${files[@]}"; do
		while ! test -e "$i"; do
			:
		done
	done

	$compiler "$@" "${files[@]}"

done
