#!/bin/bash
GREEN="\033[1;32m"
NORMAL="\033[0m"

compiler=cc
files=()

# handle args
while [ -n "$1" ]; do
	case "$1" in
		-c) # set the compiler to something other than cc
			shift
			compiler="$1"
			;;
		--)
			shift
			break
			;;
		-*)
			echo argument "$1" is not a valid argument
			;;
		*) # Assume arg is file. Pass to compiler
			files+=("$1")
			;;
	esac
	shift
done

# compile once before waiting starts
$compiler "$@" "${files[@]}"

# watch files
while inotifywait -e modify,move_self "${files[@]}"; do
	# print divider
	printf "$GREEN"
	printf "=%.0s" `seq $COLUMNS`
	printf "$NORMAL\n"

	for i in "${files[@]}"; do
		while ! test -e "$i"; do
			:
		done
	done

	$compiler "$@" "${files[@]}"

done
